version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - db-data:/rails/db # Mount the named volume to the db directory
      - ./ssl:/rails/ssl # Mount the SSL certificates directory (if needed)
    command: sh -c "bin/rails db:migrate && bin/rails assets:precompile && bin/rails server -b 0.0.0.0 -p 3000"

volumes:
  db-data: # Define the named volume for SQLite database
